### PR TITLE
Compatibility w/ 3.6.0

### PR DESCRIPTION
**Pull request by diosmosis**
Changes:
- Use SessionAuth in GoogleAuthenticator Auth implementation if user logs in via Login plugin.
- Set GoogleAuthenticator session in SessionInitializer after session is initialized.
- Put auth_code in _SESSION (not sure if needed).

### CODE REVIEW

**Comment by sgiehl** [comment]
@diosmosis most parts work now as expected. But it's possible to circumvent the need to enter an auth code by simple refreshing the page.

**Comment by diosmosis** [comment]
@sgiehl I've gotten it to work locally, but I have to use the session for API requests. Is this expected? Or should API requests be authenticated w/o two factor auth (and just the token_auth)?

**Comment by sgiehl** [comment]
API requests need to be authenticated with additional `auth_code` param if 2FA is activated for that account. See README:

```
ATTENTION: Activating Google Authenticator for an account, also requires an auth code for direct API requests with the users token auth. Use &auth_code={authcode} to do that.
```

**Comment by diosmosis** [comment]
So then when the UI makes an API request w/ just a `token_auth=`, should we bypass 2FA? Or start a session to see if the user is already authenticated?

**Comment by sgiehl** [comment]
API-Authentication with Session should work as well I guess.

**Comment by diosmosis** [comment]
I updated w/ the changes that make it work, I'm not sure how clean the code is though. I think you're suggestion before about 2FA in core is definitely the best thing to do in the long run.

**Comment by sgiehl** [comment]
Seems to work. Will do some more testing tomorrow and merge and release a new version if all is fine. Thanks for your help @diosmosis

**Comment by diosmosis** [comment]
One thing I didn't test was archiving, just realized that

**Comment by sgiehl** [comment]
I'll merge this now and do some more tiny adjustments afterwards.

**Pull request merged**
